---
title: "01_import_data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#knitr::opts_knit$set(root.dir = '/Users/dominicmason/OneDrive\ -\ UNSW/hons') #sets WD as project for all chunks - doesn't change directory for setup chunk

#install.packages("pacman")
#install.packages("ggThemeAssist")
#install.packages("ggbeeswarm")
#install.packages("rptR")
#install.packages("lme4")
#install.packages("lmerTest")
#install.packages("wesanderson")
library(lmerTest)
library(ggThemeAssist)
library(rptR)
library(lme4)

pacman::p_load(readxl, tidyr, dplyr, magrittr, lubridate, stringr, purrr)

library(ggplot2)
library(lubridate)
library(wesanderson)
library(ggbeeswarm)
#sessionInfo()
```

```{r}
source("./scripts/functions.R")
```

```{r}
##functions
#function for adding day column
add_day <- function(x) {
x %>% mutate(day = case_when (grepl("2020-01-13", date) ~ "1",
                    grepl("2020-01-14", date) ~ "2",
                    grepl("2020-01-15", date) ~ "3",
                    grepl("2020-01-16", date) ~ "4",
                    grepl("2020-01-20", date) ~ "5",
                    grepl("2020-01-21", date) ~ "6",
                    grepl("2020-01-22", date) ~ "7",
                    grepl("2020-01-23", date) ~ "8",
                    grepl("2020-02-17", date) ~ "9",
             grepl("2020-02-18", date) ~ "10",
             grepl("2020-02-19", date) ~ "11",
             grepl("2020-02-20", date) ~ "12",
             grepl("2020-02-24", date) ~ "13",
             grepl("2020-02-25", date) ~ "14",
             grepl("2020-02-26", date) ~ "15",
             grepl("2020-02-27", date) ~ "16",))
}

add_exp <- function(x) {
  x %>% mutate(exp = case_when (grepl("BLUGRE", filepath) ~ "BLUGRE"))
}

add_set <- function(x) {
 x %>% mutate(set = case_when (grepl("c1", filepath) ~ "control",
                               grepl("c2", filepath) ~ "control",
                               grepl("c3", filepath) ~ "control",
                               grepl("c4", filepath) ~ "control",
                               grepl("t1", filepath) ~ "treatment",
                               grepl("t2", filepath) ~ "treatment",
                               grepl("t3", filepath) ~ "treatment",
                               grepl("t4", filepath) ~ "treatment"))
}

add_zone <- function(x) {
  x %>%   mutate(zone = case_when (grepl("CS", test) ~ "CS",
                    grepl("NON", test) ~ "NON"))
}

add_tod <- function(x) {
  x %>% mutate(tod = case_when (grepl("Trial1", filepath) ~ "AM",
                    grepl("Trial2", filepath) ~ "NOON",
                    grepl("Trial3", filepath) ~ "PM")) 
}

#function that spreads data and adds difference
add_diff <- function(x) {
  
  x[,7] = NULL
  
  x %>% spread(type, time) %>% mutate(difference = (BASELINE - PROBE))
}

```

```{r, warning=FALSE}
## importing csv's & transforming data
path <- paste0("./Data/Day", 1:16, "/") #Change to 1:4 or 5:8 to see first and second half to go back to normal

all_path <- map(path,  ~list.files(path = .)[str_detect(list.files(path = .), ".csv")] ) %>% map2(.,path,~ paste0(.y, .x))

dat <- map(unlist(all_path), import_csv) %>% bind_rows() %>% as_tibble() %>% group_by(filepath, date, marking, type, test, unit, variable, arena) %>% summarise(total = sum(number), mean = mean(number)) %>% filter(variable == "ZONE_TIMERS") %>% group_by(type, marking, test, unit, filepath, date) %>% summarise(sum_time = sum(total), arena = unique(arena)) %>% arrange(filepath, marking, type, test) %>% mutate(time_min = if_else(type == "BASELINE", sum_time/5, sum_time/1)) %>% add_day %>% add_exp %>% add_zone %>% add_tod %>% add_set %>% mutate(day = as.numeric(day)) %>% rename(fishID = marking)

dat
```

```{r}
dat %>% filter(unit %in% c("UNIT1", "UNIT2", "UNIT3", "UNIT4", "UNIT5", "UNIT6", "PROBE1", "PROBE2")) %>%
  group_by(type, fishID, test, filepath, day) %>%
  summarise(time = mean(time_min), arena = unique(arena)) %>%
  add_diff -> dat_2probe #All the baseline, and 2 mins of probe (biologically, fish forget after 2mins)

dat %>% filter(unit %in% c("UNIT5", "UNIT6", "PROBE1", "PROBE2")) %>%
  group_by(type, fishID, test, filepath, day) %>%
  summarise(time = mean(time_min), arena = unique(arena)) %>%
  add_diff -> dat_2base #Last 10 mins of baseline and first 2 mins of probe

dat %>% filter(unit %in% c("UNIT1", "UNIT2", "UNIT3", "UNIT4", "UNIT5", "UNIT6", "PROBE1", "PROBE2","PROBE3", "PROBE4", "PROBE5")) %>%
  group_by(type, fishID, test, filepath, day) %>%
  summarise(time = mean(time_min), arena = unique(arena)) %>%
  add_diff -> dat_5probe #All the baseline and all the probe data

sex <- read.csv("./data/ID_Weight.csv") %>% rename(fishID = Fish_ID) %>% rename(sex = Sex)

left_join(sex, dat_2probe, by = "fishID") -> p2
left_join(sex, dat_2base, by = "fishID") -> b2
left_join(sex, dat_5probe, by = "fishID") -> p5

p2 %>% add_set %>% add_tod %>% filter(test == "BLUCS") -> p2cs
saveRDS(p2cs, file = "p2cs.rds")
b2%>% add_set %>% add_tod %>% filter(test == "BLUCS") -> b2cs
p5 %>% add_set %>% add_tod %>% filter(test == "BLUCS") -> p5cs

```






