---
title: "Analysis_Anxiety_Learning"
output:
  word_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---

### Load packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Package conflict causing issue with loading data, update which packages need to be loaded
#checks for installation and loads packages
pacman::p_load(tidyverse, sjPlot, lme4, lmerTest, nlme, ggplot2, rptR, emmeans, wesanderson, ggpubr, extrafonts, stargazer)

# Load custom function to extract data 
source("./Scripts/functions_learning.R")
source("./Scripts/functions_plots.R")

#load('myEnvironment_Learning_Analysis.RData')
```

### Import Anxiety
```{r, include=FALSE}

#Anxiety
Anxiety_Joined <- read.csv("./Data/Anxiety/Anxiety_Joined.csv")
```

#Import learning data
```{r, warning=FALSE}
## importing csv's & transforming data
path <- paste0("../Data/Learning/Day", 1:16, "/")

all_path <- map(path,  ~list.files(path = .)[str_detect(list.files(path = .), ".csv")] ) %>% map2(.,path,~ paste0(.y, .x))

dat <- map(unlist(all_path), import_csv) %>% bind_rows() %>% as_tibble() %>% group_by(filepath, date, marking, type, test, unit, variable, arena) %>% summarise(total = sum(number), mean = mean(number)) %>% filter(variable == "ZONE_TIMERS") %>% group_by(type, marking, test, unit, filepath, date) %>% summarise(sum_time = sum(total), arena = unique(arena)) %>% arrange(filepath, marking, type, test) %>% mutate(time_min = if_else(type == "BASELINE", sum_time/5, sum_time/1)) %>% add_day %>% add_exp %>% add_zone %>% add_tod %>% add_set %>% mutate(day = as.numeric(day)) %>% rename(fishID = marking)

dat
```

#Subset Learning data
```{r}
dat %>% filter(unit %in% c("UNIT1", "UNIT2", "UNIT3", "UNIT4", "UNIT5", "UNIT6", "PROBE1", "PROBE2")) %>%
  group_by(type, fishID, test, filepath, date) %>%
  summarise(time = mean(time_min), arena = unique(arena)) %>%
  add_diff -> dat_2probe #We will use this dataset as it takes into acocunt the first 2 mins of the probe period, which the literature says is the most important as fish tend to forget after 2 mins, however we have options below for analysis also

# dat %>% filter(unit %in% c("UNIT5", "UNIT6", "PROBE1", "PROBE2")) %>%
#   group_by(type, fishID, test, filepath, day) %>%
#   summarise(time = mean(time_min), arena = unique(arena)) %>%
#   add_diff -> dat_2base
# 
# dat %>% filter(unit %in% c("UNIT1", "UNIT2", "UNIT3", "UNIT4", "UNIT5", "UNIT6", "PROBE1", "PROBE2","PROBE3", "PROBE4", "PROBE5")) %>%
#   group_by(type, fishID, test, filepath, day) %>%
#   summarise(time = mean(time_min), arena = unique(arena)) %>%
#   add_diff -> dat_5probe
# 
# dat %>% filter(unit %in% c("UNIT1", "UNIT2", "UNIT3", "UNIT4", "UNIT5", "UNIT6", "PROBE1")) %>%
#   group_by(type, fishID, test, filepath, day) %>%
#   summarise(time = mean(time_min), arena = unique(arena)) %>%
#   add_diff -> dat_1probe

sex <- read.csv("../Data/Learning/ID_Sex_Tank.csv") %>% rename(fishID = Fish_ID) %>% rename(sex = Sex)

left_join(sex, dat_2probe, by = "fishID") -> p2
# left_join(sex, dat_2base, by = "fishID") -> b2
# left_join(sex, dat_5probe, by = "fishID") -> p5
# left_join(sex, dat_1probe, by = "fishID") -> p1


p2 %>% add_set %>% add_tod %>% filter(test == "BLUCS") -> p2cs #OUR MAIN DATASET
# b2%>% add_set %>% add_tod %>% filter(test == "BLUCS") -> b2cs
# p5 %>% add_set %>% add_tod %>% filter(test == "BLUCS") -> p5cs
# p1 %>% add_set %>% add_tod %>% filter(test == "BLUCS") -> p1cs
```

### Examine Data

```{r, include=FALSE}

str(Anxiety_Joined)


#Convert characters into factors

Anxiety_Joined$Sex <- as.factor(Anxiety_Joined$Sex)
Anxiety_Joined$Group <- as.factor(Anxiety_Joined$Group)
Anxiety_Joined$Fish_ID <- as.factor(Anxiety_Joined$Fish_ID)
Anxiety_Joined$Day <- as.factor(Anxiety_Joined$Day)
Anxiety_Joined$Tank <- as.factor(Anxiety_Joined$Tank)
```



Joining data sets
```{r}
#Our two data sets are "Anxiety_Joined" and "p2cs". We want a data frame with the variables total distance traveled and time spent in the low zone as well as the baseline, probe and difference. We also want to add the learning and anxiety ID's as well as the mean of the anxiety variables to use in our models as fixed effects. 

#First we will work with the learning dataset

str(p2cs) #rename columns to match anxiety data set

p2cs <- p2cs %>% 
  dplyr::rename(
    Sex = sex, Fish_ID = fishID
  )

# Renaming factor levels with dplyr
p2cs$Tank <- dplyr::recode_factor(p2cs$Tank, Within_Control = "Within Control", 
                                Within_Treatment = "Within Treatment")

# Assigning learning ID's using date

#Will first mutate another column to duplicate the data column, as would rather keep date in the dataset

p2cs <- p2cs %>%
 mutate(
  L.ID = date)

p2cs$L.ID <- as.character(p2cs$L.ID)

p2cs$L.ID <- dplyr::recode(p2cs$L.ID, "2020-01-13" = "1", "2020-01-14" = "1", "2020-01-15" = "1", "2020-01-16" = "1", "2020-01-20" = "2", "2020-01-21" = "2", "2020-01-22" = "2", "2020-01-23" = "2", "2020-02-17" = "3", "2020-02-18" = "3", "2020-02-19" = "3", "2020-02-20" = "3", "2020-02-23" = "4", "2020-02-24" = "4", "2020-02-25" = "4", "2020-02-26" = "4", "2020-02-27" = "4") #Assigning learning ID's

p2cs$L.ID <- as.factor(p2cs$L.ID) #Converting back to factor

class(p2cs$L.ID) #Checking

#Removing redundant columns

p2cs <- p2cs %>% mutate(set = NULL, tod = NULL)

#Anxiety dataset prep

#Need to assign learning ID's using day 

Anxiety_Joined <- Anxiety_Joined %>%
 mutate(
  A.ID = Day)

Anxiety_Joined$A.ID <- as.character(Anxiety_Joined$A.ID)

Anxiety_Joined$A.ID <- dplyr::recode(Anxiety_Joined$A.ID, "Friday1" = "1", "Friday2" = "2", "Monday3" = "3", "Friday4" = "4") #Assigning learning ID's

Anxiety_Joined$A.ID <- as.factor(Anxiety_Joined$A.ID)

#Now we need mean values for total distance traveled and time spent in the low zone

mean_tot_dist <- group_by(Anxiety_Joined, Fish_ID) %>% summarize(mean_tot_dist = mean(tot_dist)) #Mean total distance for every fish

Anxiety_Joined <- left_join(mean_tot_dist, Anxiety_Joined, by = "Fish_ID") #Joining into main dataset

mean_low_dur <- group_by(Anxiety_Joined, Fish_ID) %>% summarize(mean_low_dur = mean(low_dur)) #mean low duration for every fish

Anxiety_Joined <- left_join(mean_low_dur, Anxiety_Joined, by = "Fish_ID") #Joining into main data frame

#Now that we have our data frames with all the required information, we must now merge the two data sets

#This can be done by extracting the data that we need (in this case, from the learning data set, the fish ID, learning ID and difference between baseline and probe and from the anxiety datas et, the mean of total distance and low duration; we would also need details regarding sex and tank)

#VERY IMPORTANT ! WHEN JOINING, YOU NEED THAT UNIQUE KEY ! IN THIS CASE, FISH ID WILL NOT BE UNIQUE BECAUSE IT IS ASSOCIATED WITH THE LEARNING ID AND ANXIETY ID, THEREFORE YOU NEED ANOTHER UNIQUE ID AND USE THAT TO JOIN. HERE WE USED "UNIQUE_ID"

Learning_summary <- group_by(p2cs, Fish_ID, L.ID) %>% summarize(learning = difference) %>% mutate(Unique_ID = paste0(Fish_ID, L.ID))

Anxiety_summary <- group_by(Anxiety_Joined, Fish_ID, A.ID, Sex, Tank) %>% summarize(mean_low_dur = mean_low_dur, mean_tot_dist = mean_tot_dist, tot_dist = tot_dist, low_dur = low_dur) %>% mutate(Unique_ID = paste0(Fish_ID, A.ID))

Anxiety_Learning <- left_join(Anxiety_summary, Learning_summary, by = "Unique_ID") #Joining by unique ID !

Anxiety_Learning <- Anxiety_Learning %>% #Remove NAs (those fish that didn't undergo learning)
  filter(!is.na(Fish_ID.y))



```

#Preliminary data analysis
```{r}
#Filter data to remove NA's of fish that have no learning data

Anxiety_Learning <- Anxiety_Learning %>% filter(!is.na(Fish_ID.y))

#Relevel
Anxiety_Learning <- within(Anxiety_Learning, Tank <- relevel(Tank, ref = "Paternal"))

Model_example <- lmer(learning ~ Tank + Sex + mean_low_dur + mean_tot_dist + (1|Fish_ID.x),data = Anxiety_Learning)
summary(Model_example)
tab_model(Model_example)
hist(residuals(Model_example))


#Contrasts 
em_learning <- emmeans(Model_example, ~ Tank) 
pairs(em_learning)


#Repeatability
rpt_learning(Anxiety_Learning) -> rpt_learning_overall
rpt_learning_overall


# Calculating difference in variance between short tanks and tall tanks 
Model_learning1 <- lme(learning ~ Tank-1 + Sex + mean_low_dur + mean_tot_dist, random = ~ 1|Fish_ID.x,data = Anxiety_Learning) #mixed model without variance structure
summary(Model_learning1)
Model_learning2 <- lme(learning ~ Tank-1 + Sex + mean_low_dur + mean_tot_dist, random = ~ 1|Fish_ID.x, weights = varIdent(form=~1|Tank), data = Anxiety_Learning)
summary(Model_learning2)
anova(Model_learning1, Model_learning2) #calculating difference between two models to find difference in variance
```

#Plots
```{r}

#Example plot showing relationship between anxiety variables and learning
low_dur_learning <- ggplot(Anxiety_Learning, aes(x = mean_low_dur, y = learning,color = Tank)) +
  geom_point(alpha=0.8) +
  facet_wrap(~Sex)+
  scale_color_viridis_d()+
  geom_smooth(method=lm)+
  facet_wrap(~Tank, ncol=2)

low_dur_learning
    
    

tot_dist_learning <- ggplot(Anxiety_Learning, aes(x = mean_tot_dist, y = learning, color = Tank)) +
  geom_point(alpha=0.8) +
  facet_wrap(~Sex)+
  scale_color_viridis_d()+
  geom_smooth(method=lm)+
  facet_wrap(~Tank, ncol=2)

tot_dist_learning

# Individual plots for learning and anxiety
learning_violin <- violin_plot_custom_hamza(Anxiety_Learning, Anxiety_Learning$learning, "Difference between baseline and probe (CS+)", "Seconds") +
  geom_signif(comparisons = list(c("Maternal", "Within Treatment")), #Adding contrasts
              map_signif_level=TRUE, y_position = 45, annotations = "**")+
  geom_signif(comparisons = list(c("Paternal", "Within Treatment")), 
              map_signif_level=TRUE, y_position = 50)

counts <- Anxiety_Learning %>% group_by(Tank) %>% tally()

#n=40 x 4 measurements

learning_violin

low_dur_violin <- violin_plot_custom_hamza(Anxiety_Learning, Anxiety_Learning$low_dur, "Time spent in the low zone", "Seconds")

low_dur_violin

tot_dist_violin <- violin_plot_custom_hamza(Anxiety_Learning, Anxiety_Learning$tot_dist, "Total distance travelled", "CM")

tot_dist_violin

#Density plots

# Use semi-transparent fill
density_learning <- ggplot(Anxiety_Learning, aes(x=learning, fill=Tank)) +
  geom_density(alpha=0.5)+
  facet_grid(~Sex)+
  scale_fill_viridis_d()

density_learning
```

#Mixed effects model plotting - mean low duration
```{r}

#Model for mean_low_duration
Model_example2 <- lmer(learning ~ Tank + Sex + mean_low_dur + (1|Fish_ID.x), data = Anxiety_Learning)
summary(Model_example2)
tab_model(Model_example2)

#Calculating repeatabilities using custom made functions
rpt_learning(Anxiety_Learning) -> rpt_learning
rpt_learning

# make predictions dataframe
new_data <- data.frame(expand.grid(Tank = unique(Anxiety_Learning$Tank), Sex = unique(Anxiety_Learning$Sex), mean_low_dur = unique(Anxiety_Learning$mean_low_dur),stringsAsFactors = FALSE))

# add predictions 
new_data$learning <- predict(Model_example2, newdata = new_data, re.form=NA)

# OPTIONAL EXTRA
# get confidence and prediction intervals around mean prediction 
# get model matrix
mm <- model.matrix(terms(Model_example2), new_data)

## or newdat$distance <- mm %*% fixef(fm1)
# variance of fixed effect
pvar <- diag(mm %*% tcrossprod(vcov(Model_example2), mm))
# variance of random effects
tvar <- pvar + VarCorr(Model_example2)$Fish_ID.x[1]  
cmult <- 1.96

# add columns to dataframes
# CI gives uncertainty around fixed effects only
# PI gives uncertainty based on random effects as well!
new_data <- mutate(new_data,
                   PI_low = learning - cmult*sqrt(tvar),
                   PI_high = learning + cmult*sqrt(tvar),
                   CI_low = learning - cmult*sqrt(pvar), 
                   CI_high = learning + cmult*sqrt(pvar))

# create dataframe for new_data for each individual ####
new_data_ind <- select(Anxiety_Learning, Tank, Sex,mean_low_dur, Fish_ID.x)
# predict each individuals relationship including the random effects
new_data_ind$learning <- predict(Model_example2, new_data_ind, re.form = NULL)



# plots the mean relationship and each individual random relationship
ggplot(Anxiety_Learning) +
  geom_point(aes(mean_low_dur, learning, col = Tank), alpha = 0.1, Anxiety_Learning) +
  geom_line(aes(mean_low_dur, learning, col = Tank, group = Fish_ID.x), alpha = 0.25, new_data_ind) +
  geom_line(aes(mean_low_dur, learning, col = Tank), new_data) +
  ylab('Learning Index') +
  xlab('Mean time spent in low zone') +
  facet_wrap(~ Sex) 

```

#Mixed effects model plotting - mean tot dist
```{r}

#Model for mean_tot_distation
Model_example2 <- lmer(learning ~ Tank + Sex + mean_tot_dist + (1|Fish_ID.x), data = Anxiety_Learning)
summary(Model_example2)
tab_model(Model_example2)

#Calculating repeatabilities using custom made functions
rpt_learning(Anxiety_Learning) -> rpt_learning
rpt_learning

# make predictions dataframe
new_data <- data.frame(expand.grid(Tank = unique(Anxiety_Learning$Tank), Sex = unique(Anxiety_Learning$Sex), mean_tot_dist = unique(Anxiety_Learning$mean_tot_dist),stringsAsFactors = FALSE))

# add predictions 
new_data$learning <- predict(Model_example2, newdata = new_data, re.form=NA)

# OPTIONAL EXTRA
# get confidence and prediction intervals around mean prediction 
# get model matrix
mm <- model.matrix(terms(Model_example2), new_data)

## or newdat$distance <- mm %*% fixef(fm1)
# variance of fixed effect
pvar <- diag(mm %*% tcrossprod(vcov(Model_example2), mm))
# variance of random effects
tvar <- pvar + VarCorr(Model_example2)$Fish_ID.x[1]  
cmult <- 1.96

# add columns to dataframes
# CI gives uncertainty around fixed effects only
# PI gives uncertainty based on random effects as well!
new_data <- mutate(new_data,
                   PI_low = learning - cmult*sqrt(tvar),
                   PI_high = learning + cmult*sqrt(tvar),
                   CI_low = learning - cmult*sqrt(pvar), 
                   CI_high = learning + cmult*sqrt(pvar))

# create dataframe for new_data for each individual ####
new_data_ind <- select(Anxiety_Learning, Tank, Sex,mean_tot_dist, Fish_ID.x)
# predict each individuals relationship including the random effects
new_data_ind$learning <- predict(Model_example2, new_data_ind, re.form = NULL)



# plots the mean relationship and each individual random relationship
ggplot(Anxiety_Learning) +
  geom_point(aes(mean_tot_dist, learning, col = Tank), alpha = 0.1, Anxiety_Learning) +
  geom_line(aes(mean_tot_dist, learning, col = Tank, group = Fish_ID.x), alpha = 0.25, new_data_ind) +
  geom_line(aes(mean_tot_dist, learning, col = Tank), new_data) +
  ylab('Learning Index') +
  xlab('Mean total distance travelled') +
  facet_wrap(~ Sex) 

```





